### ISSUE TITLE
Bug: ERROR Lavalink node: '127.0.0.1', has error: 'connect ECONNREFUSED 127.0.0.1:5000'.

### ISSUE THREAD

**Issue by richardevcom** [Spiderjockey02/Discord-Bot#205]
**BUG description**
I'm getting:
```log
ERROR Lavalink node: '127.0.0.1', has error: 'connect ECONNREFUSED 127.0.0.1:5000'.
```
All my requirements, port permissions and configurations are properly set. I've tried all `localhost`, `127.0.0.1` and even public IP address, but with no luck.

Checking `/src/Lavalink/logs/spring.log` file I found this:
```log
2021-08-01 19:33:54.020 ERROR 25165 --- [XNIO-1 task-1] l.server.io.HandshakeInterceptorImpl     : Authentication failed from /127.0.0.1:56168
```

**My configuration**
Here is my `/src/Lavalink/application.yml`:
```yml
server: # REST and WS server
  port: 5000
  address: 0.0.0.0

lavalink:
  server:
    password: "youshallnotpass"
    playerUpdateInterval: 1 # How frequently to send player updates to clients, in seconds
...
```

Here is my `/src/base/Audio-Manager.js`:
```js
...
 nodes: [
             { host: '127.0.0.1', port: 5000, password: 'youshallnotpass' },
 ],
```

Here is my `/etc/systemd/system/lavalink.service` service:
```service
[Unit]
Description = Lavalink Service
After=network.target = Lavalink.service

[Service]
Type = forking
Restart=always
RestartSec=1
SuccessExitStatus=143
ExecStart = /usr/local/bin/lavalink.sh start
ExecStop = /usr/local/bin/lavalink.sh stop
ExecReload = /usr/local/bin/lavalink.sh reload

[Install]
WantedBy=multi-user.target
```

**Reproduce**
1. Follow default installation instructions and setup bot with Lavalink.
2. Make Lavalink service in `/etc/systemd/system` and start it `systemctl start lavalink`
3. Using `pm2` add and start `node .`
4. And wait for logs to prompt error mentioned above.

**Expected behavior**
Working Lavalink server and connectable bot node serice to `127.0.0.1`, `localhost` or public IP address.

**Device:**
 - OS: CentOS 8
